# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: cypress/base:8
    environment:
      - CYPRESS_RECORD_KEY: 89e32e68-daf9-4021-adf7-6b291321b884
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v3-dependencies-
      - run: yarn install

      - run: echo 'export PATH=$CIRCLE_WORKING_DIRECTORY/node_modules/.bin:$PATH' >> $BASH_ENV

      - save_cache:
          key: v3-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run format:check
      - run: yarn run test:e2e